<a href="https://colab.research.google.com/github/Julianajjss/100_days_of_code/blob/main/acidentes_de_trab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/acidentes2022_todas_causas_tipos.csv", delimiter=';', encoding='ISO-8859-1')

In [ ]:
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,405147,911178.0,2022-01-01,sábado,00:10:00,CE,222.0,"2,8",FORTALEZA,Sim,...,Masculino,1,0,0,0,"-3,73911117",-38.586875,SPRF-CE,DEL01-CE,UOP01-DEL01-CE
1,405147,911179.0,2022-01-01,sábado,00:10:00,CE,222.0,"2,8",FORTALEZA,Sim,...,Masculino,0,0,1,0,"-3,73911117",-38.586875,SPRF-CE,DEL01-CE,UOP01-DEL01-CE
2,405149,912796.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Feminino,0,1,0,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE
3,405149,912793.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Masculino,0,0,1,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE
4,405149,913204.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Não Informado,0,0,0,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330380,475374,1030683.0,2022-08-31,quarta-feira,18:00:00,PE,104.0,"82,4",AGRESTINA,Sim,...,Não Informado,0,0,0,0,"-8,414513",-35.967102,NaN,NaN,NaN
330381,475374,1030682.0,2022-08-31,quarta-feira,18:00:00,PE,104.0,"82,4",AGRESTINA,Sim,...,Ignorado,1,0,0,0,"-8,414513",-35.967102,NaN,NaN,NaN
330382,475374,1030684.0,2022-08-31,quarta-feira,18:00:00,PE,104.0,"82,4",AGRESTINA,Sim,...,Masculino,0,0,0,1,"-8,414513",-35.967102,NaN,NaN,NaN
330383,475374,1030683.0,2022-08-31,quarta-feira,18:00:00,PE,104.0,"82,4",AGRESTINA,Sim,...,Não Informado,0,0,0,0,"-8,414513",-35.967102,NaN,NaN,NaN
330384,475374,1030682.0,2022-08-31,quarta-feira,18:00:00,PE,104.0,"82,4",AGRESTINA,Sim,...,Ignorado,1,0,0,0,"-8,414513",-35.967102,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330385 entries, 0 to 330384
Data columns (total 37 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      330385 non-null  int64
 1   pesid                   299292 non-null  float64
 2   data_inversa            330385 non-null  object
 3   dia_semana              330385 non-null  object
 4   horario                 330385 non-null  object
 5   uf                      330385 non-null  object
 6   br                      329045 non-null  float64
 7   km                      329045 non-null  object
 8   municipio               330385 non-null  object
 9   causa_principal         330385 non-null  object
 10  causa_acidente          330385 non-null  object
 11  ordem_tipo_acidente     330385 non-null  int64
 12  tipo_acidente           330385 non-null  object
 13  classificacao_acidente  330385 non-null  object
 14  fase_dia                330385 non-null  object
 15  sentido_via             330385 non-null  object
 16  condicao_metereologica  330385 non-null  object
 17  tipo_pista              330385 non-null  object
 18  tracado_via             330385 non-null  object
 19  uso_solo                330385 non-null  object
 20  id_veiculo              330385 non-null  int64
 21  tipo_veiculo            330385 non-null  object
 22  marca                   315602 non-null  object
 23  ano_fabricacao_veiculo  311857 non-null  float64
 24  tipo_envolvido          330385 non-null  object
 25  estado_fisico           330385 non-null  object
 26  idade                   260487 non-null  float64
 27  sexo                    330385 non-null  object
 28  ilesos                  330385 non-null  int64
 29  feridos_leves           330385 non-null  int64
 30  feridos_graves          330385 non-null  int64
 31  mortos                  330385 non-null  int64
 32  latitude                330385 non-null  object
 33  longitude               330385 non-null  float64
 34  regional                330354 non-null  object
 35  delegacia               330250 non-null  object
 36  uop                     329727 non-null  object
dtypes: float64(5), int64(7), object(25)
memory usage: 93.3+ MB

In [ ]:
df.head()

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,405147,911178.0,2022-01-01,sábado,00:10:00,CE,222.0,"2,8",FORTALEZA,Sim,...,Masculino,1,0,0,0,"-3,73911117",-38.586875,SPRF-CE,DEL01-CE,UOP01-DEL01-CE
1,405147,911179.0,2022-01-01,sábado,00:10:00,CE,222.0,"2,8",FORTALEZA,Sim,...,Masculino,0,0,1,0,"-3,73911117",-38.586875,SPRF-CE,DEL01-CE,UOP01-DEL01-CE
2,405149,912796.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Feminino,0,1,0,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE
3,405149,912793.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Masculino,0,0,1,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE
4,405149,913204.0,2022-01-01,sábado,01:30:00,PE,104.0,63,CARUARU,Não,...,Não Informado,0,0,0,0,"-8,2698",-35.980300,SPRF-PE,DEL02-PE,UOP01-DEL02-PE

In [ ]:
df.shape

(330385, 37)

In [ ]:
df

In [ ]:
df.count()

id                        330385
pesid                     299292
data_inversa              330385
dia_semana                330385
horario                   330385
uf                        330385
br                        329045
km                        329045
municipio                 330385
causa_principal           330385
causa_acidente            330385
ordem_tipo_acidente       330385
tipo_acidente             330385
classificacao_acidente    330385
fase_dia                  330385
sentido_via               330385
condicao_metereologica    330385
tipo_pista                330385
tracado_via               330385
uso_solo                  330385
id_veiculo                330385
tipo_veiculo              330385
marca                     315602
ano_fabricacao_veiculo    311857
tipo_envolvido            330385
estado_fisico             330385
idade                     260487
sexo                      330385
ilesos                    330385
feridos_leves             330385
feridos_graves            330385
mortos                    330385
latitude                  330385
longitude                 330385
regional                  330354
delegacia                 330250
uop                       329727
dtype: int64

In [ ]:
df.causa_acidente.value_counts().head(10)

Reação tardia ou ineficiente do condutor                     42448
Velocidade Incompatível                                      34292
Ausência de reação do condutor                               32443
Condutor deixou de manter distância do veículo da frente     23054
Acessar a via sem observar a presença dos outros veículos    20767
Ingestão de álcool pelo condutor                             18350
Manobra de mudança de faixa                                  17415
Transitar na contramão                                       11988
Condutor Dormindo                                            11411
Ultrapassagem Indevida                                       10074
Name: causa_acidente, dtype: int64